import { bootstrapApplication } from '@angular/platform-browser';
import { provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideAnimations } from '@angular/platform-browser/animations';
import { importProvidersFrom } from '@angular/core';
import {
  LucideAngularModule,
  LayoutDashboard,
  ChartCandlestick,
  ChartColumn,
  ClipboardList,
  ArrowLeftRight,
  ArrowBigLeft,
  Warehouse,
  Package,
  Package2,
  TrendingUp,
  Store,
  Building,
  Building2,
  Users,
  User,
  ShoppingCart,
  Factory,
  Layers,
  GalleryVerticalEnd,
  Cpu,
  Search,
  LogOut,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  CheckCircle,
  XCircle,
  ShieldCheck,
  Settings,
  Truck,
  X,
  SquareX,
  Pause,
  Play,
  BookUser,
  IdCard,
  MapPin,
  Hash,
  Star,
  Phone,
  Mail,
  UserX,
  SquarePen,
  Loader2,
} from 'lucide-angular';

import { AppComponent } from './app/app.component';
import { routes } from './app/app.routes';
import { authInterceptor } from './app/core/interceptors/auth.interceptor';
import { errorInterceptor } from './app/core/interceptors/error.interceptor';
import { loadingInterceptor } from './app/core/interceptors/loading.interceptor';
import { translocoConfig } from './app/core/i18n/transloco.config';

bootstrapApplication(AppComponent, {
  providers: [
    provideRouter(routes, withPreloading(PreloadAllModules)),
    provideHttpClient(withInterceptors([authInterceptor, loadingInterceptor, errorInterceptor])),
    provideAnimations(),
    translocoConfig,
    importProvidersFrom(
      LucideAngularModule.pick({
        LayoutDashboard,
        ChartCandlestick,
        ChartColumn,
        ClipboardList,
        ArrowLeftRight,
        ArrowBigLeft,
        Warehouse,
        Package,
        Package2,
        TrendingUp,
        Store,
        Building,
        Building2,
        Users,
        User,
        ShoppingCart,
        Factory,
        Layers,
        GalleryVerticalEnd,
        Cpu,
        Search,
        LogOut,
        ChevronLeft,
        ChevronRight,
        ChevronDown,
        ChevronUp,
        CheckCircle,
        XCircle,
        ShieldCheck,
        Settings,
        Truck,
        X,
        SquareX,
        Pause,
        Play,
        BookUser,
        IdCard,
        MapPin,
        Hash,
        Star,
        Phone,
        Mail,
        UserX,
        SquarePen,
        Loader2,
      })
    ),
  ],
}).catch(err => console.error(err));
