# Production Docker Compose Configuration
# This extends the main docker-compose.yml for production

services:
  # PostgreSQL Database (Production)
  postgres:
    environment:
      POSTGRES_DB: gestion_emballages_prod
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./docker/postgres/backup:/backup
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Redis (Production)
  redis:
    volumes:
      - redis_prod_data:/data
    restart: always
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

  # MinIO (Production)
  minio:
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_BROWSER_REDIRECT_URL: https://minio.yourdomain.com
    volumes:
      - minio_prod_data:/data
      - ./docker/minio/config:/root/.minio
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

  # NestJS Backend (Production)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    environment:
      NODE_ENV: production
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      
      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: gestion_emballages_prod
      DB_SYNCHRONIZE: false
      DB_LOGGING: false
      DB_SSL: ${DB_SSL:-false}
      
      # Redis Configuration
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      # MinIO Configuration
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: gestion-emballages
      
      # Production Settings
      CORS_ORIGIN: ${FRONTEND_URL}
      LOG_LEVEL: warn
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      
      # Security
      SECURITY_HSTS_MAX_AGE: 31536000
      SECURITY_HSTS_INCLUDE_SUBDOMAINS: true
      
    volumes:
      - ./backend/uploads:/app/uploads:ro
      - ./logs/backend:/app/logs
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - gestion-emballages-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

  # Angular Frontend (Production)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      args:
        API_URL: ${API_URL}
        PRODUCTION: true
    volumes:
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    networks:
      - gestion-emballages-network
    depends_on:
      - backend

  # Load Balancer (HAProxy)
  loadbalancer:
    image: haproxy:2.8-alpine
    container_name: gestion-emballages-lb
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"  # HAProxy stats
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./docker/haproxy/ssl:/etc/ssl/certs:ro
    restart: always
    networks:
      - gestion-emballages-network
    depends_on:
      - frontend

  # Backup Service
  backup:
    image: postgres:15-alpine
    container_name: gestion-emballages-backup
    environment:
      PGPASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/backup/scripts:/scripts:ro
      - ./backups:/backups
      - postgres_prod_data:/var/lib/postgresql/data:ro
    command: ["/scripts/backup.sh"]
    restart: "no"
    networks:
      - gestion-emballages-network
    depends_on:
      - postgres
    profiles:
      - backup

  # Monitoring - Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: gestion-emballages-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: always
    networks:
      - gestion-emballages-network
    profiles:
      - monitoring

  # Monitoring - Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: gestion-emballages-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
    restart: always
    networks:
      - gestion-emballages-network
    depends_on:
      - prometheus
    profiles:
      - monitoring

  # Log Aggregation - Loki
  loki:
    image: grafana/loki:latest
    container_name: gestion-emballages-loki
    ports:
      - "3100:3100"
    volumes:
      - ./docker/loki/loki.yml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    networks:
      - gestion-emballages-network
    profiles:
      - monitoring

volumes:
  postgres_prod_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${POSTGRES_DATA_PATH:-./docker/data/postgres}
  redis_prod_data:
    driver: local
  minio_prod_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MINIO_DATA_PATH:-./docker/data/minio}
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  loki_data:
    driver: local

networks:
  gestion-emballages-network:
    driver: bridge
    name: gestion-emballages-prod-network